language: php

php:
  - 7.1
  - 7.2
  - 7.3

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source

script:
  - ./vendor/bin/tester ./tests/

after_failure:
  - for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
  - vendor/bin/phpstan analyse src tests
