<?php declare(strict_types=1);

namespace Forrest79\PhPgSql\Tracy;

use Forrest79\PhPgSql;
use Tracy\Helpers;

?>
<style>
	#tracy-debug div.phpgsql-panel h2 { font-size: 20px; margin: 10px 0 0; }
	#tracy-debug td.phpgsql-panel-center { text-align: center; }
	#tracy-debug td.phpgsql-panel-sql { background: white !important; }
	#tracy-debug a.tracy-editor { color: #bbb !important; font-size: 11px; }
	#tracy-debug .phpgsql-panel-binded td, #tracy-debug .phpgsql-panel-explain td { white-space: pre; }
	#tracy-debug .phpgsql-panel-binded th { position: relative; }
	#tracy-debug .phpgsql-panel-binded a { display: inline-block; width: 16px; height: 16px; vertical-align: bottom; }
	#tracy-debug .phpgsql-panel-binded a:focus { background: none; }
	#tracy-debug .phpgsql-panel-binded a svg { width: 14px; height: 14px; padding: 2px; }
	#tracy-debug .phpgsql-panel-explain td { font-size: 11px; }
	#tracy-debug .phpgsql-panel-warning { color: #f33; }
	#tracy-debug div.phpgsql-panel-warnings { font-size: 11px; margin: 5px 0 10px; }
	#tracy-debug div.phpgsql-panel-warnings span { display: inline-block; padding: 3px; background-color: #f33; color: #fff; border-radius: 3px; }
	#tracy-debug div.phpgsql-panel-warnings span a { color: #fff; text-decoration: underline; }
	#tracy-debug div.phpgsql-panel-warnings span a:hover { background-color: #f33; text-decoration: none; }
</style>

<script type="text/javascript">
	window.phpgsqlCopyToClipboard = function (copyButton) {
		const sql = copyButton.closest('table').querySelector('td').innerText.trim();
		navigator.clipboard.writeText(sql);

		const svgCopy = copyButton.innerHTML;
		copyButton.innerHTML = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 122.881 89.842" xml:space="preserve"><g><path d="M1.232,55.541c-1.533-1.388-1.652-3.756-0.265-5.289c1.388-1.534,3.756-1.652,5.29-0.265l34.053,30.878l76.099-79.699 c1.429-1.501,3.804-1.561,5.305-0.132c1.502,1.428,1.561,3.803,0.133,5.305L43.223,88.683l-0.005-0.005 c-1.396,1.468-3.716,1.563-5.227,0.196L1.232,55.541L1.232,55.541z"/></g></svg>';
		setTimeout(function () {
			copyButton.innerHTML = svgCopy;
		}, 1000);
	}
</script>

<h1>Queries: <?php echo $count, ($totalTime ? \sprintf(', time: %0.3f ms', $totalTime * 1000) : ''), ', ', \htmlspecialchars($name, ENT_NOQUOTES, 'UTF-8') ?></h1>

<?php $requestPanelId = \uniqid($name); ?>
<?php if ($longQueryCount > 0 || $repeatingQueries !== [] || $nonParsedColumnsQueries !== []): ?>
	<div class="phpgsql-panel-warnings">
		<?php if ($longQueryCount > 0): ?>
			<span>
				<?php if ($longQueryCount > 1): ?>
					There are some long run queries
				<?php else: ?>
					<a href="#phpgsql-panel-long-run-query-<?php echo $requestPanelId; ?>">There is one long run query</a>
				<?php endif ?>
			</span>
		<?php endif ?>
		<?php if ($repeatingQueries !== []): ?>
			<span>
				<a href="#phpgsql-panel-repeating-queries-<?php echo $requestPanelId; ?>">
					<?php if (\count($repeatingQueries) > 1): ?>
						There are some repeating queries
					<?php else: ?>
						There is one repeating query
					<?php endif ?>
				</a>
			</span>
		<?php endif ?>
		<?php if ($nonParsedColumnsQueries !== []): ?>
			<span>
				<a href="#phpgsql-panel-non-parsed-columns-queries-<?php echo $requestPanelId; ?>">
					<?php if (\count($nonParsedColumnsQueries) > 1): ?>
						There are some queries with non parsed columns
					<?php else: ?>
						There is one query with non parsed columns
					<?php endif ?>
				</a>
			</span>
		<?php endif ?>
	</div>
<?php endif ?>

<div class="tracy-inner phpgsql-panel">
	<table>
		<tr>
			<th>Time&nbsp;ms</th>
			<th>SQL Query</th>
			<th>Params</th>
		</tr>
		<?php
			foreach ($queries as $query):
				[$sql, $time, $explain, $source] = $query;

				$hasParams = ($sql instanceof PhPgSql\Db\Query) && ($sql->getParams() !== []);
		?>
			<tr>
				<td>
					<?php
						if ($time === FALSE) {
							echo '-';
						} else if ($time !== NULL) {
							$formattedTime = \sprintf('%0.3f', $time * 1000);
							if (($longQueryTime !== NULL) && ($time >= $longQueryTime)) {
								echo \sprintf('<strong %sclass="phpgsql-panel-warning">%s</strong>', $longQueryCount === 1 ? 'id="phpgsql-panel-long-run-query-' . $requestPanelId . '" ' : '', $formattedTime);
							} else {
								echo $formattedTime;
							}
						} else {
							echo '<em>async</em>';
						}
					?>
					<?php if ($hasParams): ?>
						<br /><a class="tracy-toggle tracy-collapsed" data-tracy-ref="^tr .phpgsql-panel-binded">binded</a>
					<?php endif ?>
					<?php if ($explain): ?>
						<br /><a class="tracy-toggle tracy-collapsed" data-tracy-ref="^tr .phpgsql-panel-explain">explain</a>
					<?php endif ?>
				</td>
				<td class="phpgsql-panel-sql">
					<?php echo ($sql instanceof PhPgSql\Db\Query) ? $queryDump($sql->getSql()) : $sql; ?>
					<?php if ($hasParams): ?>
						<table class="tracy-collapsed phpgsql-panel-binded">
							<tr>
								<th>
									<a href="javascript:void(0);" onclick="phpgsqlCopyToClipboard(this);" title="Copy to clipboard">
										<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M502.6 70.63l-61.25-61.25C435.4 3.371 427.2 0 418.7 0H255.1c-35.35 0-64 28.66-64 64l.0195 256C192 355.4 220.7 384 256 384h192c35.2 0 64-28.8 64-64V93.25C512 84.77 508.6 76.63 502.6 70.63zM464 320c0 8.836-7.164 16-16 16H255.1c-8.838 0-16-7.164-16-16L239.1 64.13c0-8.836 7.164-16 16-16h128L384 96c0 17.67 14.33 32 32 32h47.1V320zM272 448c0 8.836-7.164 16-16 16H63.1c-8.838 0-16-7.164-16-16L47.98 192.1c0-8.836 7.164-16 16-16H160V128H63.99c-35.35 0-64 28.65-64 64l.0098 256C.002 483.3 28.66 512 64 512h192c35.2 0 64-28.8 64-64v-32h-47.1L272 448z"/></svg>
									</a>
									Binded query:
								</th>
							</tr>
							<tr>
								<td><?php echo $queryDump($sql->getSql(), $sql->getParams()); ?></td>
							</tr>
						</table>
					<?php endif ?>
					<?php if ($explain !== NULL): ?>
						<table class="tracy-collapsed phpgsql-panel-explain">
							<tr>
								<th>Explain:</th>
							</tr>
							<tr>
								<td><?php foreach ($explain as $row) echo \htmlspecialchars(\str_replace("\t", '', $row['QUERY PLAN']), ENT_NOQUOTES, 'UTF-8') . PHP_EOL; ?></td>
							</tr>
						</table>
					<?php endif ?>
					<?php if ($source !== NULL) {
						echo Helpers::editorLink($source['file'], $source['line']);
					} ?>
				</td>
				<td>
					<?php if ($hasParams) echo $paramsDump($sql->getParams()); ?>
				</td>
			</tr>
		<?php endforeach ?>
	</table>
	<?php if ($repeatingQueries !== []): ?>
		<h2 id="phpgsql-panel-repeating-queries-<?php echo $requestPanelId; ?>">Repeating queries: <?php echo \count($repeatingQueries); ?></h2>
		<table>
			<tr>
				<th>Count</th>
				<th>SQL Query</th>
			</tr>
			<?php foreach ($repeatingQueries as $query => $count): ?>
				<tr>
					<td class="phpgsql-panel-center">
						<?php echo $count; ?>x
					</td>
					<td class="phpgsql-panel-sql">
						<?php echo $queryDump($query); ?>
					</td>
				</tr>
			<?php endforeach ?>
		</table>
	<?php endif ?>
	<?php if ($nonParsedColumnsQueries !== []): ?>
		<h2 id="phpgsql-panel-non-parsed-columns-queries-<?php echo $requestPanelId; ?>">Non parsed columns queries: <?php echo \count($nonParsedColumnsQueries); ?></h2>
		<table>
			<tr>
				<th>SQL Query</th>
				<th>Params</th>
				<th>Non&nbsp;parsed&nbsp;columns</th>
			</tr>
			<?php
				foreach ($nonParsedColumnsQueries as $item):
					[$query, $nonParsedColumns] = $item;
			?>
				<tr>
					<td class="phpgsql-panel-sql">
						<?php echo $queryDump($query->getSql()); ?>
					</td>
					<td>
						<?php if ($query->getParams() !== []) echo $paramsDump($query->getParams()); ?>
					</td>
					<td>
						<pre><?php echo \implode(PHP_EOL, $nonParsedColumns); ?></pre>
					</td>
				</tr>
			<?php endforeach ?>
		</table>
	<?php endif ?>
</div>
