<?php declare(strict_types=1);

namespace Forrest79\PhPgSql\Tracy;

use Forrest79\PhPgSql;
use Tracy\Helpers;

?>
<style>
	#tracy-debug div.phpgsql-panel h2 { font-size: 20px; margin: 10px 0 0; }
	#tracy-debug td.phpgsql-panel-center { text-align: center; }
	#tracy-debug td.phpgsql-panel-sql { background: white !important; }
	#tracy-debug a.tracy-editor { color: #bbb !important; font-size: 11px; }
	#tracy-debug a.phpgsql-panel-button { display: inline-block; width: 12px; height: 12px; line-height: 12px; }
	#tracy-debug a.phpgsql-panel-button:focus { background: none; }
	#tracy-debug .phpgsql-panel-binded td, #tracy-debug .phpgsql-panel-explain td { white-space: pre; }
	#tracy-debug .phpgsql-panel-binded th { position: relative; }
	#tracy-debug .phpgsql-panel-explain td { font-size: 11px; }
	#tracy-debug .phpgsql-panel-warning { background-color: #ff6363 !important; color: #fff !important; }
	#tracy-debug div.phpgsql-panel-warnings { font-size: 11px; margin: 5px 0 10px; }
	#tracy-debug div.phpgsql-panel-warnings span { display: inline-block; padding: 3px; background-color: #f33; color: #fff; border-radius: 3px; }
	#tracy-debug div.phpgsql-panel-warnings span a { color: #fff; text-decoration: underline; }
	#tracy-debug div.phpgsql-panel-warnings span a:hover { background-color: #f33; text-decoration: none; }
</style>

<script type="text/javascript">
	let Tracy = window.Tracy = window.Tracy || {};
	Tracy.phpgsqlCopyToClipboard = function (copyButton, binded) {
		const sql = binded ? copyButton.closest('tr').querySelector('td[data-binded-sql-query]').innerText.trim() : copyButton.closest('tr').querySelector('span[data-sql-query]').innerText.trim();
		navigator.clipboard.writeText(sql);

		const svgCopy = copyButton.innerHTML;
		copyButton.innerHTML = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path d="M438.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L160 338.7 393.4 105.4c12.5-12.5 32.8-12.5 45.3 0z"/></svg>';
		setTimeout(function () {
			copyButton.innerHTML = svgCopy;
		}, 1000);
	}
</script>

<h1>Queries: <?php echo $count, ($totalTimeMs ? \sprintf(', time: %0.3f ms', $totalTimeMs) : ''), ', ', \htmlspecialchars($name, ENT_NOQUOTES, 'UTF-8') ?></h1>

<?php $requestPanelId = \uniqid($name); ?>
<?php if ($longQueryCount > 0 || $repeatingQueries !== [] || $nonParsedColumnsQueries !== []): ?>
	<div class="phpgsql-panel-warnings">
		<?php if ($longQueryCount > 0): ?>
			<span>
				<?php if ($longQueryCount > 1): ?>
					There are some long run queries
				<?php else: ?>
					<a href="#phpgsql-panel-long-run-query-<?php echo $requestPanelId; ?>">There is one long run query</a>
				<?php endif ?>
			</span>
		<?php endif ?>
		<?php if ($repeatingQueries !== []): ?>
			<span>
				<a href="#phpgsql-panel-repeating-queries-<?php echo $requestPanelId; ?>">
					<?php if (\count($repeatingQueries) > 1): ?>
						There are some repeating queries
					<?php else: ?>
						There is one repeating query
					<?php endif ?>
				</a>
			</span>
		<?php endif ?>
		<?php if ($nonParsedColumnsQueries !== []): ?>
			<span>
				<a href="#phpgsql-panel-non-parsed-columns-queries-<?php echo $requestPanelId; ?>">
					<?php if (\count($nonParsedColumnsQueries) > 1): ?>
						There are some queries with non parsed columns
					<?php else: ?>
						There is one query with non parsed columns
					<?php endif ?>
				</a>
			</span>
		<?php endif ?>
	</div>
<?php endif ?>

<div class="tracy-inner phpgsql-panel">
	<table>
		<tr>
			<th></th>
			<th>Time&nbsp;ms</th>
			<th>SQL Query</th>
			<th>Params</th>
		</tr>
		<?php
			foreach ($queries as $query):
				[$sql, $timeMs, $explain, $source] = $query;

				$hasParams = ($sql instanceof PhPgSql\Db\Query) && ($sql->getParams() !== []);
		?>
			<tr>
				<td>
					<a href="javascript:void(0);" onclick="Tracy.phpgsqlCopyToClipboard(this, false);" class="phpgsql-panel-button" title="Copy SQL query to clipboard">
						<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><!--!Font Awesome Free 6.7.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2025 Fonticons, Inc.--><path d="M384 336l-192 0c-8.8 0-16-7.2-16-16l0-256c0-8.8 7.2-16 16-16l140.1 0L400 115.9 400 320c0 8.8-7.2 16-16 16zM192 384l192 0c35.3 0 64-28.7 64-64l0-204.1c0-12.7-5.1-24.9-14.1-33.9L366.1 14.1c-9-9-21.2-14.1-33.9-14.1L192 0c-35.3 0-64 28.7-64 64l0 256c0 35.3 28.7 64 64 64zM64 128c-35.3 0-64 28.7-64 64L0 448c0 35.3 28.7 64 64 64l192 0c35.3 0 64-28.7 64-64l0-32-48 0 0 32c0 8.8-7.2 16-16 16L64 464c-8.8 0-16-7.2-16-16l0-256c0-8.8 7.2-16 16-16l32 0 0-48-32 0z"/></svg>
					</a>
					<?php if ($hasParams): ?>
						<br />
						<a href="javascript:void(0);" onclick="Tracy.phpgsqlCopyToClipboard(this, true);" class="phpgsql-panel-button" title="Copy binded SQL query to clipboard">
							<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path d="M208 0L332.1 0c12.7 0 24.9 5.1 33.9 14.1l67.9 67.9c9 9 14.1 21.2 14.1 33.9L448 336c0 26.5-21.5 48-48 48l-192 0c-26.5 0-48-21.5-48-48l0-288c0-26.5 21.5-48 48-48zM48 128l80 0 0 64-64 0 0 256 192 0 0-32 64 0 0 48c0 26.5-21.5 48-48 48L48 512c-26.5 0-48-21.5-48-48L0 176c0-26.5 21.5-48 48-48z"/></svg>
						</a>
					<?php endif ?>
				</td>
				<td<?php if (($longQueryTimeMs !== NULL) && ($timeMs >= $longQueryTimeMs)): ?> class="phpgsql-panel-warning"<?php endif ?>>
					<?php
						if ($timeMs === FALSE) {
							echo '-';
						} else if ($timeMs !== NULL) {
							$formattedTime = \sprintf('%0.3f', $timeMs);
							if (($longQueryTimeMs !== NULL) && ($timeMs >= $longQueryTimeMs)) {
								echo \sprintf('<strong %s>%s</strong>', ($longQueryCount === 1) ? 'id="phpgsql-panel-long-run-query-' . $requestPanelId . '" ' : '', $formattedTime);
							} else {
								echo $formattedTime;
							}
						} else {
							echo '<em>async</em>';
						}
					?>
					<?php if ($hasParams): ?>
						<br />
						<a class="tracy-toggle tracy-collapsed" data-tracy-ref="^tr .phpgsql-panel-binded">binded</a>
					<?php endif ?>
					<?php if ($explain): ?>
						<br />
						<a class="tracy-toggle tracy-collapsed" data-tracy-ref="^tr .phpgsql-panel-explain">explain</a>
					<?php endif ?>
				</td>
				<td class="phpgsql-panel-sql">
					<span data-sql-query><?php echo ($sql instanceof PhPgSql\Db\Query) ? $queryDump($sql->getSql()) : $sql; ?></span>
					<?php if ($hasParams): ?>
						<table class="tracy-collapsed phpgsql-panel-binded">
							<tr>
								<th>
									Binded query:
								</th>
							</tr>
							<tr>
								<td data-binded-sql-query><?php echo $queryDump($sql->getSql(), $sql->getParams()); ?></td>
							</tr>
						</table>
					<?php endif ?>
					<?php if ($explain !== NULL): ?>
						<table class="tracy-collapsed phpgsql-panel-explain">
							<tr>
								<th>Explain:</th>
							</tr>
							<tr>
								<td><?php foreach ($explain as $row) echo \htmlspecialchars(\str_replace("\t", '', $row['QUERY PLAN']), ENT_NOQUOTES, 'UTF-8') . PHP_EOL; ?></td>
							</tr>
						</table>
					<?php endif ?>
					<?php if ($source !== NULL) {
						echo Helpers::editorLink($source['file'], $source['line']);
					} ?>
				</td>
				<td>
					<?php if ($hasParams) echo $paramsDump($sql->getParams()); ?>
				</td>
			</tr>
		<?php endforeach ?>
	</table>
	<?php if ($repeatingQueries !== []): ?>
		<h2 id="phpgsql-panel-repeating-queries-<?php echo $requestPanelId; ?>">Repeating queries: <?php echo \count($repeatingQueries); ?></h2>
		<table>
			<tr>
				<th>Count</th>
				<th>SQL Query</th>
			</tr>
			<?php foreach ($repeatingQueries as $query => $count): ?>
				<tr>
					<td class="phpgsql-panel-center">
						<?php echo $count; ?>x
					</td>
					<td class="phpgsql-panel-sql">
						<?php echo $queryDump($query); ?>
					</td>
				</tr>
			<?php endforeach ?>
		</table>
	<?php endif ?>
	<?php if ($nonParsedColumnsQueries !== []): ?>
		<h2 id="phpgsql-panel-non-parsed-columns-queries-<?php echo $requestPanelId; ?>">Non parsed columns queries: <?php echo \count($nonParsedColumnsQueries); ?></h2>
		<table>
			<tr>
				<th>SQL Query</th>
				<th>Params</th>
				<th>Non&nbsp;parsed&nbsp;columns</th>
			</tr>
			<?php
				foreach ($nonParsedColumnsQueries as $item):
					[$query, $nonParsedColumns] = $item;
			?>
				<tr>
					<td class="phpgsql-panel-sql">
						<?php echo $queryDump($query->getSql()); ?>
					</td>
					<td>
						<?php if ($query->getParams() !== []) echo $paramsDump($query->getParams()); ?>
					</td>
					<td>
						<pre><?php echo \implode(PHP_EOL, $nonParsedColumns); ?></pre>
					</td>
				</tr>
			<?php endforeach ?>
		</table>
	<?php endif ?>
</div>
