<?php declare(strict_types=1);

namespace Forrest79\PhPgSql\Tracy;

use Forrest79\PhPgSql;

?>
<style class="tracy-debug">
	#tracy-debug div.phpgsql-panel h2 { font-size: 20px; margin: 10px 0 0; }
	#tracy-debug td.phpgsql-panel-center { text-align: center; }
	#tracy-debug td.phpgsql-panel-sql { background: white !important; }
	#tracy-debug .phpgsql-panel-binded td, #tracy-debug .phpgsql-panel-explain td { white-space: pre; }
	#tracy-debug .phpgsql-panel-explain td { font-size: 11px; }
	#tracy-debug .phpgsql-panel-warning { color: #f33; }
	#tracy-debug div.phpgsql-panel-warnings { font-size: 11px; margin: 5px 0 10px; }
	#tracy-debug div.phpgsql-panel-warnings span { display: inline-block; padding: 3px; background-color: #f33; color: #fff; border-radius: 3px; }
	#tracy-debug div.phpgsql-panel-warnings span a { color: #fff; text-decoration: underline; }
	#tracy-debug div.phpgsql-panel-warnings span a:hover { background-color: #f33; text-decoration: none; }
</style>

<h1>Queries: <?php echo $count, ($totalTime ? \sprintf(', time: %0.3f ms', $totalTime * 1000) : ''), ', ', \htmlspecialchars($name, ENT_NOQUOTES, 'UTF-8') ?></h1>

<?php $requestPanelId = uniqid($name); ?>
<?php if ($longQueryCount > 0 || $repeatingQueries !== [] || $nonParsedColumnsQueries !== []): ?>
	<div class="phpgsql-panel-warnings">
		<?php if ($longQueryCount > 0): ?>
			<span>
				<?php if ($longQueryCount > 1): ?>
					There are some long run queries
				<?php else: ?>
					<a href="#phpgsql-panel-long-run-query-<?php echo $requestPanelId; ?>">There is one long run query</a>
				<?php endif ?>
			</span>
		<?php endif ?>
		<?php if ($repeatingQueries !== []): ?>
			<span>
				<a href="#phpgsql-panel-repeating-queries-<?php echo $requestPanelId; ?>">
					<?php if (count($repeatingQueries) > 1): ?>
						There are some repeating queries
					<?php else: ?>
						There is one repeating query
					<?php endif ?>
				</a>
			</span>
		<?php endif ?>
		<?php if ($nonParsedColumnsQueries !== []): ?>
			<span>
				<a href="#phpgsql-panel-non-parsed-columns-queries-<?php echo $requestPanelId; ?>">
					<?php if (count($nonParsedColumnsQueries) > 1): ?>
						There are some queries with non parsed columns
					<?php else: ?>
						There is one query with non parsed columns
					<?php endif ?>
				</a>
			</span>
		<?php endif ?>
	</div>
<?php endif ?>

<div class="tracy-inner phpgsql-panel">
	<table>
		<tr>
			<th>Time&nbsp;ms</th>
			<th>SQL Query</th>
			<th>Params</th>
		</tr>
		<?php
			foreach ($queries as $query):
				[$sql, $time, $explain] = $query;

				$hasParams = ($sql instanceof PhPgSql\Db\Query) && ($sql->getParams() !== []);
		?>
			<tr>
				<td>
					<?php
						if ($time === FALSE) {
							echo '-';
						} else if ($time !== NULL) {
							$formattedTime = \sprintf('%0.3f', $time * 1000);
							if (($longQueryTime !== NULL) && ($time >= $longQueryTime)) {
								echo \sprintf('<strong %sclass="phpgsql-panel-warning">%s</strong>', $longQueryCount === 1 ? 'id="phpgsql-panel-long-run-query-' . $requestPanelId . '" ' : '', $formattedTime);
							} else {
								echo $formattedTime;
							}
						} else {
							echo '<em>async</em>';
						}
					?>
					<?php if ($hasParams): ?>
						<br /><a class="tracy-toggle tracy-collapsed" data-tracy-ref="^tr .phpgsql-panel-binded">binded</a>
					<?php endif ?>
					<?php if ($explain): ?>
						<br /><a class="tracy-toggle tracy-collapsed" data-tracy-ref="^tr .phpgsql-panel-explain">explain</a>
					<?php endif ?>
				</td>
				<td class="phpgsql-panel-sql">
					<?php echo ($sql instanceof PhPgSql\Db\Query) ? $queryDump($sql->getSql()) : $sql; ?>
					<?php if ($hasParams): ?>
						<table class="tracy-collapsed phpgsql-panel-binded">
							<tr>
								<th>Binded query:</th>
							</tr>
							<tr>
								<td><?php echo $queryDump($sql->getSql(), $sql->getParams()); ?></td>
							</tr>
						</table>
					<?php endif ?>
					<?php if ($explain !== NULL): ?>
						<table class="tracy-collapsed phpgsql-panel-explain">
							<tr>
								<th>Explain:</th>
							</tr>
							<tr>
								<td><?php foreach ($explain as $row) echo \htmlspecialchars(\str_replace("\t", '', $row['QUERY PLAN']), ENT_NOQUOTES, 'UTF-8') . PHP_EOL; ?></td>
							</tr>
						</table>
					<?php endif ?>
				</td>
				<td>
					<?php if ($hasParams) echo $paramsDump($sql->getParams()); ?>
				</td>
			</tr>
		<?php endforeach ?>
	</table>
	<?php if ($repeatingQueries !== []): ?>
		<h2 id="phpgsql-panel-repeating-queries-<?php echo $requestPanelId; ?>">Repeating queries: <?php echo \count($repeatingQueries); ?></h2>
		<table>
			<tr>
				<th>Count</th>
				<th>SQL Query</th>
			</tr>
			<?php foreach ($repeatingQueries as $query => $count): ?>
				<tr>
					<td class="phpgsql-panel-center">
						<?php echo $count; ?>x
					</td>
					<td class="phpgsql-panel-sql">
						<?php echo $queryDump($query); ?>
					</td>
				</tr>
			<?php endforeach ?>
		</table>
	<?php endif ?>
	<?php if ($nonParsedColumnsQueries !== []): ?>
		<h2 id="phpgsql-panel-non-parsed-columns-queries-<?php echo $requestPanelId; ?>">Non parsed columns queries: <?php echo \count($nonParsedColumnsQueries); ?></h2>
		<table>
			<tr>
				<th>SQL Query</th>
				<th>Params</th>
				<th>Non&nbsp;parsed&nbsp;columns</th>
			</tr>
			<?php
				foreach ($nonParsedColumnsQueries as $item):
					[$query, $nonParsedColumns] = $item;
			?>
				<tr>
					<td class="phpgsql-panel-sql">
						<?php echo $queryDump($query->getSql()); ?>
					</td>
					<td>
						<?php if ($query->getParams() !== []) echo $paramsDump($query->getParams()); ?>
					</td>
					<td>
						<pre><?php echo \implode(PHP_EOL, $nonParsedColumns); ?></pre>
					</td>
				</tr>
			<?php endforeach ?>
		</table>
	<?php endif ?>
</div>
